final List<Map<String, dynamic>> products = [
  {
    'name': 'Yamaha Soul GT',
    'image':
        'https://awsimages.detik.net.id/community/media/visual/2023/04/26/kembaran-yamaha-soul-gt-meluncur-di-brazil-1.png?w=1200',
    'description':
        'This is the description for Yamaha Soul GT. It is a high-performance motorbike suitable for all terrains.',
    'specsification_1': 'Tipe: Air cooled 4-stroke, SOHC, Single cylinder',
    'specsification_2': 'Kapasitas: 125cc',
    'specsification_3': 'Diameter X Langkah: 52,4 mm x 57,9 mm',
    'specsification_4': 'Rasio Kompresi: 9,5 : 1',
    'specsification_5': 'Pengapian: TCI (Transistor Control Ignition)',
    'specsification_6': 'Sistem Bahan Bakar: Fuel injection',
    'specsification_7': 'Starter: Electric',
    'specsification_8':
        'Transmsi: Kering, Centrifugal automatic, V-belt automatic',
    'specsification_9': 'P x L x T: 1870mm X 685mm X 1070mm',
    'specsification_10': 'Tinggi Tempat Duduk: 760mm',
    'specsification_11': 'Jarak Terendah ke Tanah: 135mm',
    'specsification_12': 'Jarak Sumbu Roda: 1260mm',
    'specsification_13': 'Kapasitas tangki: 4,2L',
    'specsification_14': 'Rangka: Underbone',
    'specsification_15': 'Suspensi depan: Teleskopik',
    'specsification_16': 'Suspensi belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 80/80-14M/C 43P',
    'specsification_18': 'Ban Belakang: 100/70- 14M/C 51P',
    'specsification_19': 'Rem Depan: Single disc brake',
    'specsification_20': 'Rem Belakang: Drum brake',
    'price': 16300000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Yamaha Grand Filano',
    'image':
        'https://imgcdn.oto.com/large/gallery/exterior/84/2720/yamaha-grand-filano-hybrid-connected-slant-front-view-full-image-247658.jpg',
    'description':
        'This is the description for Yamaha Grand Filano. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1': 'Tipe Mesin: Pendingin Udara, 4-Langkah, SOHC',
    'specsification_2': 'Susunan Silinder: Silinder Tunggal',
    'specsification_3': 'Diameter x Langkah: 52,4 x 57,9 mm',
    'specsification_4': 'Perbandingan Kompresi: 11,0 : 1',
    'specsification_5': 'Volume Silinder: 124,86 cc',
    'specsification_6': 'Daya Maksimum: 6,1 kW / 6.500 rpm',
    'specsification_7': 'Torsi Maksimum: 10,4 Nm / 5.000 rpm',
    'specsification_8': 'Kapasitas Oli Mesin: Total = 0,84 L; Berkala = 0,80 L',
    'specsification_9': 'Sistem Bahan Bakar: Fuel Injection',
    'specsification_10': 'Tipe Kopling: Kopling Sentrifugal, Kering',
    'specsification_11': 'Tipe Transmisi: V-Belt Otomatis',
    'specsification_12': 'Sistem Starter: Elektrik',
    'specsification_13': 'Sistem Pelumasan: Basah',
    'specsification_14': 'Tipe Rangka: Underbone',
    'specsification_15': 'Suspensi Depan: Teleskopik',
    'specsification_16': 'Suspensi Belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 110/70-12 47L',
    'specsification_18': 'Ban Belakang: 110/70-12 47L',
    'specsification_19': 'Tipe Ban: Tubeless',
    'specsification_20': 'Rem Depan: Rem Cakram',
    'specsification_21': 'Rem Belakang: Rem Tromol',
    'specsification_22': 'P X L X T: 1820 x 685 x 1155 mm',
    'specsification_23': 'Jarak Sumbu Roda: 1280 mm',
    'specsification_24': 'Jarak Terendah ke Tanah: 125 mm',
    'specsification_25': 'Tinggi Tempat Duduk: 790 mm',
    'specsification_26': 'Berat Isi: 100 Kg',
    'specsification_27': 'Kapasitas Tangki Bensin: 4,4 L',
    'specsification_28': 'Sistem Pengapian: TCI',
    'specsification_29': 'Battery: YTZ6V',
    'specsification_30': 'Tipe Busi: CR6HSA',
    'price': 27800000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Yamaha FreeGo',
    'image':
        'https://mobile.yamahabrm.co.id/pics/images_600x600_240424/MATIC/freego-125/freego-125-Standard-Metallic_Red-600x600.jpg',
    'description':
        'This is the description for Yamaha FreeGo. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1': 'Tipe Mesin: Air Cooled 4-Stroke, SOHC',
    'specsification_2': 'Susunan Silinder: Single Cylinder',
    'specsification_3': 'Diameter x Langkah: 52,4 x 57,9 mm',
    'specsification_4': 'Perbandingan Kompresi: 9,5 : 1',
    'specsification_5': 'Volume Silinder: 125 cc',
    'specsification_6': 'Daya Maksimum: 7,0 kW / 8000 rpm',
    'specsification_7': 'Torsi Maksimum: 9,5 Nm / 5500 rpm',
    'specsification_8': 'Sistem Starter: Electric Starter',
    'specsification_9': 'Sistem Pelumasan: Wet Sump',
    'specsification_10':
        'Kapasitas Oli Mesin: Total = 0,84 L; Berkala = 0,80 L',
    'specsification_11': 'Sistem Bahan Bakar: Fuel Injection',
    'specsification_12': 'Tipe Kopling: Dry, Centrifugal Automatic',
    'specsification_13': 'Tipe Transmisi: V-belt Automatic',
    'specsification_14': 'Tipe Rangka: Underbone',
    'specsification_15': 'Suspensi Depan: Telescopic Fork',
    'specsification_16': 'Suspensi Belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 100/90 - 12M/C 59J - Tubeless',
    'specsification_18': 'Ban Belakang: 110/90-12M/C 64L - Tubeless',
    'specsification_19': 'Rem Depan: Disc Brake',
    'specsification_20': 'Rem Belakang: Drum Brake',
    'specsification_21': 'P x L x T: 1905 x 690 x 1115 mm',
    'specsification_22': 'Jarak Sumbu Roda: 1275 mm',
    'specsification_23': 'Tinggi Tempat Duduk: 780 mm',
    'specsification_24':
        'Berat Isi: 101 Kg (FreeGo 125), 102 Kg (FreeGo 125 Connected)',
    'specsification_25': 'Kapasitas Tangki Bensin: 4,2 L',
    'specsification_26': 'Jarak Terendah ke Tanah: 135 mm',
    'specsification_27': 'Tipe Busi: NGK/ CR6HSA',
    'specsification_28': 'Sistem Pengapian: TCI',
    'specsification_29':
        'Battery: YTZ4V, GTZ4V, NTZ4V (FreeGo 125), YTZ6V (FreeGo 125 Connected)',
    'price': 2350000000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Yamaha Nmax',
    'image':
        'https://images.tokopedia.net/img/cache/700/OJWluG/2022/8/1/b1b2d80f-0dfd-44d4-8e60-3d3497f757bf.jpg',
    'description':
        'This is the description for Yamaha Nmax. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1': 'Tipe Mesin: Liquid cooled 4-stroke, SOHC , VVA',
    'specsification_2': 'Jumlah/Posisi Silinder: Single Cylinder',
    'specsification_3': 'Volume Silinder: 155.09 cc',
    'specsification_4': 'Diameter x Langkah: 58 mm x 58.7 mm',
    'specsification_5': 'Perbandingan Kompresi: 11.6 : 1',
    'specsification_6': 'Daya Maksimum: 11.3 kW / 8000 rpm',
    'specsification_7': 'Torsi Maksimum: 13.9 Nm / 6500 rpm',
    'specsification_8': 'Sistem Starter: Electric Starter',
    'specsification_9': 'Sistem Pelumasan: Wet Sump',
    'specsification_10': 'Kapasitas Oli Mesin: 0,9 L (Periodical Change)',
    'specsification_11': 'Sistem Bahan Bakar: Fuel Injection',
    'specsification_12': 'Tipe Kopling: Single Dry Clutch',
    'specsification_13': 'Tipe Transmisi: Automatic',
    'specsification_14': 'Tipe Rangka: Underbone',
    'specsification_15': 'Suspensi Depan: Telescopic',
    'specsification_16': 'Suspensi Belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 110/70 - 13 M/C 48P',
    'specsification_18': 'Ban Belakang: 130/70 - 13 M/C 63P',
    'specsification_19': 'Rem Depan: Hydraulic Single Disc Brake',
    'specsification_20': 'Rem Belakang: Hydraulic Single Disc Brake',
    'specsification_21': 'P x L x T: 1935 x 740 x 1160 mm',
    'specsification_22': 'Jarak Sumbu Roda: 1340 mm',
    'specsification_23': 'Jarak Terendah Ke Tanah: 124 mm',
    'specsification_24': 'Tinggi Tempat Duduk: 765 mm',
    'specsification_25':
        'Berat Isi: 130 kg (Standard & Connected Version), 132 kg (Connected/ABS Version)',
    'specsification_26': 'Kapasitas Tangki Bensin: 7.1 L',
    'specsification_27': 'Sistem Pengapian: TCI',
    'specsification_28': 'Battery: YTZ6V/YTZ7V',
    'specsification_29': 'Tipe Busi: NGK/CPR8EA-9',
    'price': 36300000000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Honda Scoopy',
    'image':
        'https://images.tokopedia.net/img/cache/700/OJWluG/2022/8/1/b1b2d80f-0dfd-44d4-8e60-3d3497f757bf.jpg',
    'description':
        'This is the description for Honda Scoopy. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1':
        'Tipe Mesin: 4 - Langkah, SOHC dengan Pendingin Udara, eSP',
    'specsification_2':
        'Sistem Suplai Bahan Bakar: PGM-FI (Programmed Fuel Injection)',
    'specsification_3': 'Diameter X Langkah: 47 x 63,1 mm',
    'specsification_4': 'Tipe Tranmisi: Otomatis, V-Matic',
    'specsification_5': 'Rasio Kompresi: 10 : 1',
    'specsification_6': 'Daya Maksimum: 6,6 kW (9 PS) / 7.500 rpm',
    'specsification_7': 'Torsi Maksimum: 9,3 Nm (0,95 kgf.m) / 5.500 rpm',
    'specsification_8':
        'Tipe Starter: Elektrik & kick Starter / Elektrik (Tipe Smart Key)',
    'specsification_9': 'Tipe Kopling: Otomatis, Sentrifugal, Tipe Kering',
    'specsification_10':
        'Tipe Rangka: Underbone - eSAF (enhance Smart Architecture Frame)',
    'specsification_11': 'Tipe Suspensi Depan: Teleskopik',
    'specsification_12':
        'Tipe Suspensi Belakang: Lengan Ayun dengan Peredam Kejut Tunggal',
    'specsification_13': 'Ukuran Ban Depan: 100/90 – 12 59J (Tubeless)',
    'specsification_14': 'Ukuran Ban Belakang: 110/90 – 12 64J (Tubeless)',
    'specsification_15': 'Rem Depan: Cakram Hidrolik dengan Piston Tunggal',
    'specsification_16': 'Rem Belakang: Tromol',
    'specsification_17': 'Sistem Pengereman: Combi Brake System',
    'specsification_18': 'P x L x T: 1.864 x 683 x 1.075 mm',
    'specsification_19': 'Tinggi Tempat Duduk: 746 mm',
    'specsification_20': 'Jarak Sumbu Roda: 1.251 mm',
    'specsification_21': 'Jarak Terendah Ke Tanah: 145 mm',
    'specsification_22': 'Curb Weight: 95 kg dan 94 kg (tipe SmartKey)',
    'specsification_23': 'Kapasitas Tangki Bahan Bakar: 4,2 L',
    'specsification_24':
        'Kapasitas Minyak Pelumas: 0,65 Liter (Penggantian Periodik)',
    'specsification_25': 'Tipe Baterai Atau Aki: MF 12V-5Ah',
    'specsification_26': 'Sistem Pengapian: Full Transistorized',
    'specsification_27': 'Tipe Busi: NGK MR9C-9N',
    'price': 22425000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Honda',
  },
  {
    'name': 'Honda Vario',
    'image':
        'https://images.tokopedia.net/img/cache/700/OJWluG/2022/8/2/3056ca82-72ae-485b-8bec-a7726752878d.jpg?ect=4g',
    'description':
        'This is the description for Honda Vario. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1': 'Tipe Mesin: 4-Stroke, SOHC, eSP+',
    'specsification_2': 'Sistem Pendingin: Pendingin Cairan',
    'specsification_3': 'Volume Langkah: 157 cc',
    'specsification_4':
        'Sistem Suplai Bahan Bakar: PGM-FI (Programmed Fuel Injection)',
    'specsification_5': 'Diameter x Langkah: 60 x 55,5 mm',
    'specsification_6': 'Tipe Transmisi: Otomatis, V-Matic',
    'specsification_7': 'Daya Maksimum: 11,3 kW / 8.500 rpm',
    'specsification_8': 'Torsi Maksimum: 13,8 Nm / 7.000 rpm',
    'specsification_9': 'Sistem Starter: Elektrik',
    'specsification_10': 'Tipe Rangka: Underbone',
    'specsification_11': 'Suspensi Depan: Telescopic',
    'specsification_12':
        'Suspensi Belakang: Swing arm dengan peredam kejut tunggal',
    'specsification_13': 'Ban Depan: 100/80 - 14M/C 48P Tubeless',
    'specsification_14': 'Ban Belakang: 120/70 - 14M/C 61P Tubeless',
    'specsification_15': 'Rem Depan: Cakram Hidrolik, Piston Tunggal',
    'specsification_16': 'Rem Belakang: Tromol',
    'specsification_17': 'Sistem Pengereman: CBS (Combi Brake System)',
    'specsification_18': 'P x L x T: 1929 x 679 x 1088 mm',
    'specsification_19': 'Jarak Sumbu Roda: 1280 mm',
    'specsification_20': 'Tinggi Tempat Duduk: 778 mm',
    'specsification_21': 'Jarak Terendah ke Tanah: 140 mm',
    'specsification_22': 'Berat Kosong: 115 kg',
    'specsification_23': 'Kapasitas Tangki Bensin: 5,5 L',
    'price': 23110000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Honda',
  },
 {
    'name': 'Honda Beat',
    'image':
        'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tokopedia.com%2Fcatalog%2Fhonda-68817%2Fhonda-beat-sporty-cbs-iss&psig=AOvVaw0EA_CSsAptH6NAHMP-8XPp&ust=1718262014690000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKihgfi-1YYDFQAAAAAdAAAAABAE',
    'description':
        'This is the description for Honda Beat. It is a stylish and efficient scooter perfect for city commuting.',
    'specsification_1': 'Tipe Mesin: 4-Stroke, SOHC, Air Cooled',
    'specsification_2': 'Volume Silinder: 110 cc',
    'specsification_3': 'Daya Maksimum: 6.4 kW / 7500 rpm',
    'specsification_4': 'Torsi Maksimum: 9.3 Nm / 5500 rpm',
    'specsification_5': 'Sistem Starter: Electric & Kick Starter',
    'specsification_6': 'Sistem Bahan Bakar: PGM-FI',
    'specsification_7': 'Tipe Transmisi: V-Matic',
    'specsification_8': 'P x L x T: 1877 mm x 669 mm x 1062 mm',
    'specsification_9': 'Jarak Sumbu Roda: 1256 mm',
    'specsification_10': 'Jarak Terendah ke Tanah: 147 mm',
    'specsification_11': 'Tinggi Tempat Duduk: 740 mm',
    'specsification_12': 'Berat Isi: 93 Kg',
    'specsification_13': 'Kapasitas Tangki Bensin: 4.2 L',
    'specsification_14': 'Rem Depan: Cakram Hidrolik',
    'specsification_15': 'Rem Belakang: Tromol',
    'specsification_16': 'Suspensi Depan: Teleskopik',
    'specsification_17': 'Suspensi Belakang: Lengan Ayun dengan Peredam Kejut Tunggal',
    'specsification_18': 'Ban Depan: 80/90-14M/C 40P',
    'specsification_19': 'Ban Belakang: 90/90-14M/C 46P',
    'price': 17000000.0,
    'rating': 4.6,
    'isFavorite': false,
    'brand': 'Honda',
  }
];
