final List<Map<String, dynamic>> products = [
  {
    'name': 'Yamaha Soul GT',
    'image':
        'https://awsimages.detik.net.id/community/media/visual/2023/04/26/kembaran-yamaha-soul-gt-meluncur-di-brazil-1.png?w=1200',
    'description':
        'This is the description for Yamaha Soul GT. It is a high-performance motorbike suitable for all terrains.',
    'specsification_1': 'Tipe: Air cooled 4-stroke, SOHC, Single cylinder',
    'specsification_2': 'Kapasitas: 125cc',
    'specsification_3': 'Diameter X Langkah: 52,4 mm x 57,9 mm',
    'specsification_4': 'Rasio Kompresi: 9,5 : 1',
    'specsification_5': 'Pengapian: TCI (Transistor Control Ignition)',
    'specsification_6': 'Sistem Bahan Bakar: Fuel injection',
    'specsification_7': 'Starter: Electric',
    'specsification_8':
        'Transmsi: Kering, Centrifugal automatic, V-belt automatic',
    'specsification_9': 'P x L x T: 1870mm X 685mm X 1070mm',
    'specsification_10': 'Tinggi Tempat Duduk: 760mm',
    'specsification_11': 'Jarak Terendah ke Tanah: 135mm',
    'specsification_12': 'Jarak Sumbu Roda: 1260mm',
    'specsification_13': 'Kapasitas tangki: 4,2L',
    'specsification_14': 'Rangka: Underbone',
    'specsification_15': 'Suspensi depan: Teleskopik',
    'specsification_16': 'Suspensi belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 80/80-14M/C 43P',
    'specsification_18': 'Ban Belakang: 100/70- 14M/C 51P',
    'specsification_19': 'Rem Depan: Single disc brake',
    'specsification_20': 'Rem Belakang: Drum brake',
    'price': 15000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Yamaha Grand Filano',
    'image':
        'https://imgcdn.oto.com/large/gallery/exterior/84/2720/yamaha-grand-filano-hybrid-connected-slant-front-view-full-image-247658.jpg',
    'description':
        'This is the description for Yamaha Grand Filano. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1': 'Tipe Mesin: Pendingin Udara, 4-Langkah, SOHC',
    'specsification_2': 'Susunan Silinder: Silinder Tunggal',
    'specsification_3': 'Diameter x Langkah: 52,4 x 57,9 mm',
    'specsification_4': 'Perbandingan Kompresi: 11,0 : 1',
    'specsification_5': 'Volume Silinder: 124,86 cc',
    'specsification_6': 'Daya Maksimum: 6,1 kW / 6.500 rpm',
    'specsification_7': 'Torsi Maksimum: 10,4 Nm / 5.000 rpm',
    'specsification_8': 'Kapasitas Oli Mesin: Total = 0,84 L; Berkala = 0,80 L',
    'specsification_9': 'Sistem Bahan Bakar: Fuel Injection',
    'specsification_10': 'Tipe Kopling: Kopling Sentrifugal, Kering',
    'specsification_11': 'Tipe Transmisi: V-Belt Otomatis',
    'specsification_12': 'Sistem Starter: Elektrik',
    'specsification_13': 'Sistem Pelumasan: Basah',
    'specsification_14': 'Tipe Rangka: Underbone',
    'specsification_15': 'Suspensi Depan: Teleskopik',
    'specsification_16': 'Suspensi Belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 110/70-12 47L',
    'specsification_18': 'Ban Belakang: 110/70-12 47L',
    'specsification_19': 'Tipe Ban: Tubeless',
    'specsification_20': 'Rem Depan: Rem Cakram',
    'specsification_21': 'Rem Belakang: Rem Tromol',
    'specsification_22': 'P X L X T: 1820 x 685 x 1155 mm',
    'specsification_23': 'Jarak Sumbu Roda: 1280 mm',
    'specsification_24': 'Jarak Terendah ke Tanah: 125 mm',
    'specsification_25': 'Tinggi Tempat Duduk: 790 mm',
    'specsification_26': 'Berat Isi: 100 Kg',
    'specsification_27': 'Kapasitas Tangki Bensin: 4,4 L',
    'specsification_28': 'Sistem Pengapian: TCI',
    'specsification_29': 'Battery: YTZ6V',
    'specsification_30': 'Tipe Busi: CR6HSA',
    'price': 15000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Yamaha FreeGo',
    'image':
        'https://mobile.yamahabrm.co.id/pics/images_600x600_240424/MATIC/freego-125/freego-125-Standard-Metallic_Red-600x600.jpg',
    'description':
        'This is the description for Yamaha FreeGo. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1': 'Tipe Mesin: Air Cooled 4-Stroke, SOHC',
    'specsification_2': 'Susunan Silinder: Single Cylinder',
    'specsification_3': 'Diameter x Langkah: 52,4 x 57,9 mm',
    'specsification_4': 'Perbandingan Kompresi: 9,5 : 1',
    'specsification_5': 'Volume Silinder: 125 cc',
    'specsification_6': 'Daya Maksimum: 7,0 kW / 8000 rpm',
    'specsification_7': 'Torsi Maksimum: 9,5 Nm / 5500 rpm',
    'specsification_8': 'Sistem Starter: Electric Starter',
    'specsification_9': 'Sistem Pelumasan: Wet Sump',
    'specsification_10':
        'Kapasitas Oli Mesin: Total = 0,84 L; Berkala = 0,80 L',
    'specsification_11': 'Sistem Bahan Bakar: Fuel Injection',
    'specsification_12': 'Tipe Kopling: Dry, Centrifugal Automatic',
    'specsification_13': 'Tipe Transmisi: V-belt Automatic',
    'specsification_14': 'Tipe Rangka: Underbone',
    'specsification_15': 'Suspensi Depan: Telescopic Fork',
    'specsification_16': 'Suspensi Belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 100/90 - 12M/C 59J - Tubeless',
    'specsification_18': 'Ban Belakang: 110/90-12M/C 64L - Tubeless',
    'specsification_19': 'Rem Depan: Disc Brake',
    'specsification_20': 'Rem Belakang: Drum Brake',
    'specsification_21': 'P x L x T: 1905 x 690 x 1115 mm',
    'specsification_22': 'Jarak Sumbu Roda: 1275 mm',
    'specsification_23': 'Tinggi Tempat Duduk: 780 mm',
    'specsification_24':
        'Berat Isi: 101 Kg (FreeGo 125), 102 Kg (FreeGo 125 Connected)',
    'specsification_25': 'Kapasitas Tangki Bensin: 4,2 L',
    'specsification_26': 'Jarak Terendah ke Tanah: 135 mm',
    'specsification_27': 'Tipe Busi: NGK/ CR6HSA',
    'specsification_28': 'Sistem Pengapian: TCI',
    'specsification_29':
        'Battery: YTZ4V, GTZ4V, NTZ4V (FreeGo 125), YTZ6V (FreeGo 125 Connected)',
    'price': 15000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Yamaha Nmax',
    'image':
        'https://images.tokopedia.net/img/cache/700/OJWluG/2022/8/1/b1b2d80f-0dfd-44d4-8e60-3d3497f757bf.jpg',
    'description':
        'This is the description for Yamaha Nmax. It is a high-performance scooter suitable for urban commuting.',
    'specsification_1': 'Tipe Mesin: Liquid cooled 4-stroke, SOHC , VVA',
    'specsification_2': 'Jumlah/Posisi Silinder: Single Cylinder',
    'specsification_3': 'Volume Silinder: 155.09 cc',
    'specsification_4': 'Diameter x Langkah: 58 mm x 58.7 mm',
    'specsification_5': 'Perbandingan Kompresi: 11.6 : 1',
    'specsification_6': 'Daya Maksimum: 11.3 kW / 8000 rpm',
    'specsification_7': 'Torsi Maksimum: 13.9 Nm / 6500 rpm',
    'specsification_8': 'Sistem Starter: Electric Starter',
    'specsification_9': 'Sistem Pelumasan: Wet Sump',
    'specsification_10': 'Kapasitas Oli Mesin: 0,9 L (Periodical Change)',
    'specsification_11': 'Sistem Bahan Bakar: Fuel Injection',
    'specsification_12': 'Tipe Kopling: Single Dry Clutch',
    'specsification_13': 'Tipe Transmisi: Automatic',
    'specsification_14': 'Tipe Rangka: Underbone',
    'specsification_15': 'Suspensi Depan: Telescopic',
    'specsification_16': 'Suspensi Belakang: Unit Swing',
    'specsification_17': 'Ban Depan: 110/70 - 13 M/C 48P',
    'specsification_18': 'Ban Belakang: 130/70 - 13 M/C 63P',
    'specsification_19': 'Rem Depan: Hydraulic Single Disc Brake',
    'specsification_20': 'Rem Belakang: Hydraulic Single Disc Brake',
    'specsification_21': 'P x L x T: 1935 x 740 x 1160 mm',
    'specsification_22': 'Jarak Sumbu Roda: 1340 mm',
    'specsification_23': 'Jarak Terendah Ke Tanah: 124 mm',
    'specsification_24': 'Tinggi Tempat Duduk: 765 mm',
    'specsification_25':
        'Berat Isi: 130 kg (Standard & Connected Version), 132 kg (Connected/ABS Version)',
    'specsification_26': 'Kapasitas Tangki Bensin: 7.1 L',
    'specsification_27': 'Sistem Pengapian: TCI',
    'specsification_28': 'Battery: YTZ6V/YTZ7V',
    'specsification_29': 'Tipe Busi: NGK/CPR8EA-9',
    'price': 15000.0,
    'rating': 4.5,
    'isFavorite': false,
    'brand': 'Yamaha',
  },
  {
    'name': 'Honda CB500F',
    'image': 'https://via.placeholder.com/600x400',
    'description':
        'This is the description for Honda CB500F. A top choice for city commuting.',
    'price': 10000.0,
    'rating': 4.2,
    'isFavorite': false,
    'brand': 'Honda',
  },
  {
    'name': 'Suzuki GSX-S750',
    'image': 'https://via.placeholder.com/600x400',
    'description':
        'This is the description for Suzuki GSX-S750. A top choice for city commuting.',
    'price': 11000.0,
    'rating': 4.1,
    'isFavorite': false,
    'brand': 'Suzuki',
  },
];
